// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD38S4L3L0mDsPb8UC--bolHNNh9MAgoM4',
    appId: '1:575469670531:web:4f61a7929b405224b34bb6',
    messagingSenderId: '575469670531',
    projectId: 'socailmediaapp-c1fd4',
    authDomain: 'socailmediaapp-c1fd4.firebaseapp.com',
    storageBucket: 'socailmediaapp-c1fd4.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDptlDcINVGHHeVr128SO9AsqJ5fAqK3qc',
    appId: '1:575469670531:android:d4ed8611ed5e8958b34bb6',
    messagingSenderId: '575469670531',
    projectId: 'socailmediaapp-c1fd4',
    storageBucket: 'socailmediaapp-c1fd4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxbeCkUgxrlbvghqhNWJwvnEr2xkQZ7Bg',
    appId: '1:575469670531:ios:0906763b461329beb34bb6',
    messagingSenderId: '575469670531',
    projectId: 'socailmediaapp-c1fd4',
    storageBucket: 'socailmediaapp-c1fd4.appspot.com',
    iosBundleId: 'com.example.socialApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDxbeCkUgxrlbvghqhNWJwvnEr2xkQZ7Bg',
    appId: '1:575469670531:ios:0906763b461329beb34bb6',
    messagingSenderId: '575469670531',
    projectId: 'socailmediaapp-c1fd4',
    storageBucket: 'socailmediaapp-c1fd4.appspot.com',
    iosBundleId: 'com.example.socialApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD38S4L3L0mDsPb8UC--bolHNNh9MAgoM4',
    appId: '1:575469670531:web:b08cc331bf3b3532b34bb6',
    messagingSenderId: '575469670531',
    projectId: 'socailmediaapp-c1fd4',
    authDomain: 'socailmediaapp-c1fd4.firebaseapp.com',
    storageBucket: 'socailmediaapp-c1fd4.appspot.com',
  );
}
